name: pyCFS
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.0
  - adjusttext=0.7.3.1
  - alsa-lib=1.2.3.2
  - arrow-cpp=4.0.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.151
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcftools=1.9
  - biopython=1.78
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - colorama=0.4.6
  - cryptography=36.0.1
  - curl=7.71.1
  - cycler=0.11.0
  - dbus=1.13.18
  - decorator=5.1.1
  - et_xmlfile=1.0.1
  - expat=2.4.9
  - fontconfig=2.13.1
  - fonttools=4.29.1
  - freetype=2.10.4
  - gdbm=1.18
  - gettext=0.21.0
  - gflags=2.2.2
  - glib=2.68.4
  - glib-tools=2.68.4
  - glog=0.4.0
  - grpc-cpp=1.37.1
  - gsl=2.5
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - htslib=1.9
  - icu=68.1
  - idna=3.3
  - ipython=7.31.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.3.2
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.71.1
  - libcxx=12.0.0
  - libcxxabi=12.0.0
  - libdeflate=1.0
  - libedit=3.1.20221030
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.68.4
  - libgomp=12.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.5
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.15.8
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.14.1
  - libtiff=4.2.0
  - libutf8proc=2.6.1
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - matplotlib-venn=0.11.6
  - munkres=1.1.4
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.3
  - networkx=2.6.3
  - nspr=4.33
  - nss=3.74
  - numpy=1.21.5
  - olefile=0.46
  - openpyxl=3.0.9
  - openssl=1.1.1t
  - orc=1.6.7
  - packaging=21.3
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - perl=5.34.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.2.2
  - prompt-toolkit=3.0.27
  - ptyprocess=0.7.0
  - pyarrow=4.0.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pysam=0.15.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.3
  - qt=5.12.9
  - re2=2021.04.01
  - readline=8.1.2
  - requests=2.27.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.37.2
  - statsmodels=0.13.2
  - threadpoolctl=3.1.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.1.1
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - venn=0.1.3
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - pandas==1.1.3
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - upsetplot==0.6.0

